// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: MyFruitsOut.proto

package netty.protobuf;

public final class MyFruitsOut {
  private MyFruitsOut() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface MyDataTypeOrBuilder extends
      // @@protoc_insertion_point(interface_extends:MyDataType)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     *标识传递的是哪一个类型
     * </pre>
     *
     * <code>.MyDataType.DataType data_type = 1;</code>
     */
    int getDataTypeValue();
    /**
     * <pre>
     *标识传递的是哪一个类型
     * </pre>
     *
     * <code>.MyDataType.DataType data_type = 1;</code>
     */
    MyDataType.DataType getDataType();

    /**
     * <code>.Apple apple = 2;</code>
     */
    boolean hasApple();
    /**
     * <code>.Apple apple = 2;</code>
     */
    Apple getApple();
    /**
     * <code>.Apple apple = 2;</code>
     */
    AppleOrBuilder getAppleOrBuilder();

    /**
     * <code>.Orange orange = 3;</code>
     */
    boolean hasOrange();
    /**
     * <code>.Orange orange = 3;</code>
     */
    Orange getOrange();
    /**
     * <code>.Orange orange = 3;</code>
     */
    OrangeOrBuilder getOrangeOrBuilder();

    public MyDataType.DataBodyCase getDataBodyCase();
  }
  /**
   * Protobuf type {@code MyDataType}
   */
  public  static final class MyDataType extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:MyDataType)
      MyDataTypeOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use MyDataType.newBuilder() to construct.
    private MyDataType(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private MyDataType() {
      dataType_ = 0;
    }

    @Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private MyDataType(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {
              int rawValue = input.readEnum();

              dataType_ = rawValue;
              break;
            }
            case 18: {
              Apple.Builder subBuilder = null;
              if (dataBodyCase_ == 2) {
                subBuilder = ((Apple) dataBody_).toBuilder();
              }
              dataBody_ =
                  input.readMessage(Apple.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom((Apple) dataBody_);
                dataBody_ = subBuilder.buildPartial();
              }
              dataBodyCase_ = 2;
              break;
            }
            case 26: {
              Orange.Builder subBuilder = null;
              if (dataBodyCase_ == 3) {
                subBuilder = ((Orange) dataBody_).toBuilder();
              }
              dataBody_ =
                  input.readMessage(Orange.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom((Orange) dataBody_);
                dataBody_ = subBuilder.buildPartial();
              }
              dataBodyCase_ = 3;
              break;
            }
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return MyFruitsOut.internal_static_MyDataType_descriptor;
    }

    @Override
    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return MyFruitsOut.internal_static_MyDataType_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              MyDataType.class, Builder.class);
    }

    /**
     * Protobuf enum {@code MyDataType.DataType}
     */
    public enum DataType
        implements com.google.protobuf.ProtocolMessageEnum {
      /**
       * <code>AppleType = 0;</code>
       */
      AppleType(0),
      /**
       * <code>OrangeTyoe = 1;</code>
       */
      OrangeTyoe(1),
      UNRECOGNIZED(-1),
      ;

      /**
       * <code>AppleType = 0;</code>
       */
      public static final int AppleType_VALUE = 0;
      /**
       * <code>OrangeTyoe = 1;</code>
       */
      public static final int OrangeTyoe_VALUE = 1;


      public final int getNumber() {
        if (this == UNRECOGNIZED) {
          throw new IllegalArgumentException(
              "Can't get the number of an unknown enum value.");
        }
        return value;
      }

      /**
       * @deprecated Use {@link #forNumber(int)} instead.
       */
      @Deprecated
      public static DataType valueOf(int value) {
        return forNumber(value);
      }

      public static DataType forNumber(int value) {
        switch (value) {
          case 0: return AppleType;
          case 1: return OrangeTyoe;
          default: return null;
        }
      }

      public static com.google.protobuf.Internal.EnumLiteMap<DataType>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static final com.google.protobuf.Internal.EnumLiteMap<
          DataType> internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<DataType>() {
              public DataType findValueByNumber(int number) {
                return DataType.forNumber(number);
              }
            };

      public final com.google.protobuf.Descriptors.EnumValueDescriptor
          getValueDescriptor() {
        return getDescriptor().getValues().get(ordinal());
      }
      public final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }
      public static final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptor() {
        return MyDataType.getDescriptor().getEnumTypes().get(0);
      }

      private static final DataType[] VALUES = values();

      public static DataType valueOf(
          com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
        if (desc.getType() != getDescriptor()) {
          throw new IllegalArgumentException(
            "EnumValueDescriptor is not for this type.");
        }
        if (desc.getIndex() == -1) {
          return UNRECOGNIZED;
        }
        return VALUES[desc.getIndex()];
      }

      private final int value;

      private DataType(int value) {
        this.value = value;
      }

      // @@protoc_insertion_point(enum_scope:MyDataType.DataType)
    }

    private int dataBodyCase_ = 0;
    private Object dataBody_;
    public enum DataBodyCase
        implements com.google.protobuf.Internal.EnumLite {
      APPLE(2),
      ORANGE(3),
      DATABODY_NOT_SET(0);
      private final int value;
      private DataBodyCase(int value) {
        this.value = value;
      }
      /**
       * @deprecated Use {@link #forNumber(int)} instead.
       */
      @Deprecated
      public static DataBodyCase valueOf(int value) {
        return forNumber(value);
      }

      public static DataBodyCase forNumber(int value) {
        switch (value) {
          case 2: return APPLE;
          case 3: return ORANGE;
          case 0: return DATABODY_NOT_SET;
          default: return null;
        }
      }
      public int getNumber() {
        return this.value;
      }
    };

    public DataBodyCase
    getDataBodyCase() {
      return DataBodyCase.forNumber(
          dataBodyCase_);
    }

    public static final int DATA_TYPE_FIELD_NUMBER = 1;
    private int dataType_;
    /**
     * <pre>
     *标识传递的是哪一个类型
     * </pre>
     *
     * <code>.MyDataType.DataType data_type = 1;</code>
     */
    public int getDataTypeValue() {
      return dataType_;
    }
    /**
     * <pre>
     *标识传递的是哪一个类型
     * </pre>
     *
     * <code>.MyDataType.DataType data_type = 1;</code>
     */
    public DataType getDataType() {
      @SuppressWarnings("deprecation")
      DataType result = DataType.valueOf(dataType_);
      return result == null ? DataType.UNRECOGNIZED : result;
    }

    public static final int APPLE_FIELD_NUMBER = 2;
    /**
     * <code>.Apple apple = 2;</code>
     */
    public boolean hasApple() {
      return dataBodyCase_ == 2;
    }
    /**
     * <code>.Apple apple = 2;</code>
     */
    public Apple getApple() {
      if (dataBodyCase_ == 2) {
         return (Apple) dataBody_;
      }
      return Apple.getDefaultInstance();
    }
    /**
     * <code>.Apple apple = 2;</code>
     */
    public AppleOrBuilder getAppleOrBuilder() {
      if (dataBodyCase_ == 2) {
         return (Apple) dataBody_;
      }
      return Apple.getDefaultInstance();
    }

    public static final int ORANGE_FIELD_NUMBER = 3;
    /**
     * <code>.Orange orange = 3;</code>
     */
    public boolean hasOrange() {
      return dataBodyCase_ == 3;
    }
    /**
     * <code>.Orange orange = 3;</code>
     */
    public Orange getOrange() {
      if (dataBodyCase_ == 3) {
         return (Orange) dataBody_;
      }
      return Orange.getDefaultInstance();
    }
    /**
     * <code>.Orange orange = 3;</code>
     */
    public OrangeOrBuilder getOrangeOrBuilder() {
      if (dataBodyCase_ == 3) {
         return (Orange) dataBody_;
      }
      return Orange.getDefaultInstance();
    }

    private byte memoizedIsInitialized = -1;
    @Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (dataType_ != DataType.AppleType.getNumber()) {
        output.writeEnum(1, dataType_);
      }
      if (dataBodyCase_ == 2) {
        output.writeMessage(2, (Apple) dataBody_);
      }
      if (dataBodyCase_ == 3) {
        output.writeMessage(3, (Orange) dataBody_);
      }
      unknownFields.writeTo(output);
    }

    @Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (dataType_ != DataType.AppleType.getNumber()) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(1, dataType_);
      }
      if (dataBodyCase_ == 2) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, (Apple) dataBody_);
      }
      if (dataBodyCase_ == 3) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(3, (Orange) dataBody_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @Override
    public boolean equals(final Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof MyDataType)) {
        return super.equals(obj);
      }
      MyDataType other = (MyDataType) obj;

      boolean result = true;
      result = result && dataType_ == other.dataType_;
      result = result && getDataBodyCase().equals(
          other.getDataBodyCase());
      if (!result) return false;
      switch (dataBodyCase_) {
        case 2:
          result = result && getApple()
              .equals(other.getApple());
          break;
        case 3:
          result = result && getOrange()
              .equals(other.getOrange());
          break;
        case 0:
        default:
      }
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + DATA_TYPE_FIELD_NUMBER;
      hash = (53 * hash) + dataType_;
      switch (dataBodyCase_) {
        case 2:
          hash = (37 * hash) + APPLE_FIELD_NUMBER;
          hash = (53 * hash) + getApple().hashCode();
          break;
        case 3:
          hash = (37 * hash) + ORANGE_FIELD_NUMBER;
          hash = (53 * hash) + getOrange().hashCode();
          break;
        case 0:
        default:
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static MyDataType parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static MyDataType parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static MyDataType parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static MyDataType parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static MyDataType parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static MyDataType parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static MyDataType parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static MyDataType parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static MyDataType parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static MyDataType parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static MyDataType parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static MyDataType parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(MyDataType prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @Override
    protected Builder newBuilderForType(
        BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code MyDataType}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:MyDataType)
        MyDataTypeOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return MyFruitsOut.internal_static_MyDataType_descriptor;
      }

      @Override
      protected FieldAccessorTable
          internalGetFieldAccessorTable() {
        return MyFruitsOut.internal_static_MyDataType_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                MyDataType.class, Builder.class);
      }

      // Construct using netty.protobuf.MyFruitsOut.MyDataType.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @Override
      public Builder clear() {
        super.clear();
        dataType_ = 0;

        dataBodyCase_ = 0;
        dataBody_ = null;
        return this;
      }

      @Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return MyFruitsOut.internal_static_MyDataType_descriptor;
      }

      @Override
      public MyDataType getDefaultInstanceForType() {
        return MyDataType.getDefaultInstance();
      }

      @Override
      public MyDataType build() {
        MyDataType result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @Override
      public MyDataType buildPartial() {
        MyDataType result = new MyDataType(this);
        result.dataType_ = dataType_;
        if (dataBodyCase_ == 2) {
          if (appleBuilder_ == null) {
            result.dataBody_ = dataBody_;
          } else {
            result.dataBody_ = appleBuilder_.build();
          }
        }
        if (dataBodyCase_ == 3) {
          if (orangeBuilder_ == null) {
            result.dataBody_ = dataBody_;
          } else {
            result.dataBody_ = orangeBuilder_.build();
          }
        }
        result.dataBodyCase_ = dataBodyCase_;
        onBuilt();
        return result;
      }

      @Override
      public Builder clone() {
        return (Builder) super.clone();
      }
      @Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      @Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      @Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      @Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      @Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      @Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof MyDataType) {
          return mergeFrom((MyDataType)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(MyDataType other) {
        if (other == MyDataType.getDefaultInstance()) return this;
        if (other.dataType_ != 0) {
          setDataTypeValue(other.getDataTypeValue());
        }
        switch (other.getDataBodyCase()) {
          case APPLE: {
            mergeApple(other.getApple());
            break;
          }
          case ORANGE: {
            mergeOrange(other.getOrange());
            break;
          }
          case DATABODY_NOT_SET: {
            break;
          }
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @Override
      public final boolean isInitialized() {
        return true;
      }

      @Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        MyDataType parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (MyDataType) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int dataBodyCase_ = 0;
      private Object dataBody_;
      public DataBodyCase
          getDataBodyCase() {
        return DataBodyCase.forNumber(
            dataBodyCase_);
      }

      public Builder clearDataBody() {
        dataBodyCase_ = 0;
        dataBody_ = null;
        onChanged();
        return this;
      }


      private int dataType_ = 0;
      /**
       * <pre>
       *标识传递的是哪一个类型
       * </pre>
       *
       * <code>.MyDataType.DataType data_type = 1;</code>
       */
      public int getDataTypeValue() {
        return dataType_;
      }
      /**
       * <pre>
       *标识传递的是哪一个类型
       * </pre>
       *
       * <code>.MyDataType.DataType data_type = 1;</code>
       */
      public Builder setDataTypeValue(int value) {
        dataType_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       *标识传递的是哪一个类型
       * </pre>
       *
       * <code>.MyDataType.DataType data_type = 1;</code>
       */
      public DataType getDataType() {
        @SuppressWarnings("deprecation")
        DataType result = DataType.valueOf(dataType_);
        return result == null ? DataType.UNRECOGNIZED : result;
      }
      /**
       * <pre>
       *标识传递的是哪一个类型
       * </pre>
       *
       * <code>.MyDataType.DataType data_type = 1;</code>
       */
      public Builder setDataType(DataType value) {
        if (value == null) {
          throw new NullPointerException();
        }
        
        dataType_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <pre>
       *标识传递的是哪一个类型
       * </pre>
       *
       * <code>.MyDataType.DataType data_type = 1;</code>
       */
      public Builder clearDataType() {
        
        dataType_ = 0;
        onChanged();
        return this;
      }

      private com.google.protobuf.SingleFieldBuilderV3<
          Apple, Apple.Builder, AppleOrBuilder> appleBuilder_;
      /**
       * <code>.Apple apple = 2;</code>
       */
      public boolean hasApple() {
        return dataBodyCase_ == 2;
      }
      /**
       * <code>.Apple apple = 2;</code>
       */
      public Apple getApple() {
        if (appleBuilder_ == null) {
          if (dataBodyCase_ == 2) {
            return (Apple) dataBody_;
          }
          return Apple.getDefaultInstance();
        } else {
          if (dataBodyCase_ == 2) {
            return appleBuilder_.getMessage();
          }
          return Apple.getDefaultInstance();
        }
      }
      /**
       * <code>.Apple apple = 2;</code>
       */
      public Builder setApple(Apple value) {
        if (appleBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          dataBody_ = value;
          onChanged();
        } else {
          appleBuilder_.setMessage(value);
        }
        dataBodyCase_ = 2;
        return this;
      }
      /**
       * <code>.Apple apple = 2;</code>
       */
      public Builder setApple(
          Apple.Builder builderForValue) {
        if (appleBuilder_ == null) {
          dataBody_ = builderForValue.build();
          onChanged();
        } else {
          appleBuilder_.setMessage(builderForValue.build());
        }
        dataBodyCase_ = 2;
        return this;
      }
      /**
       * <code>.Apple apple = 2;</code>
       */
      public Builder mergeApple(Apple value) {
        if (appleBuilder_ == null) {
          if (dataBodyCase_ == 2 &&
              dataBody_ != Apple.getDefaultInstance()) {
            dataBody_ = Apple.newBuilder((Apple) dataBody_)
                .mergeFrom(value).buildPartial();
          } else {
            dataBody_ = value;
          }
          onChanged();
        } else {
          if (dataBodyCase_ == 2) {
            appleBuilder_.mergeFrom(value);
          }
          appleBuilder_.setMessage(value);
        }
        dataBodyCase_ = 2;
        return this;
      }
      /**
       * <code>.Apple apple = 2;</code>
       */
      public Builder clearApple() {
        if (appleBuilder_ == null) {
          if (dataBodyCase_ == 2) {
            dataBodyCase_ = 0;
            dataBody_ = null;
            onChanged();
          }
        } else {
          if (dataBodyCase_ == 2) {
            dataBodyCase_ = 0;
            dataBody_ = null;
          }
          appleBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>.Apple apple = 2;</code>
       */
      public Apple.Builder getAppleBuilder() {
        return getAppleFieldBuilder().getBuilder();
      }
      /**
       * <code>.Apple apple = 2;</code>
       */
      public AppleOrBuilder getAppleOrBuilder() {
        if ((dataBodyCase_ == 2) && (appleBuilder_ != null)) {
          return appleBuilder_.getMessageOrBuilder();
        } else {
          if (dataBodyCase_ == 2) {
            return (Apple) dataBody_;
          }
          return Apple.getDefaultInstance();
        }
      }
      /**
       * <code>.Apple apple = 2;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          Apple, Apple.Builder, AppleOrBuilder>
          getAppleFieldBuilder() {
        if (appleBuilder_ == null) {
          if (!(dataBodyCase_ == 2)) {
            dataBody_ = Apple.getDefaultInstance();
          }
          appleBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              Apple, Apple.Builder, AppleOrBuilder>(
                  (Apple) dataBody_,
                  getParentForChildren(),
                  isClean());
          dataBody_ = null;
        }
        dataBodyCase_ = 2;
        onChanged();;
        return appleBuilder_;
      }

      private com.google.protobuf.SingleFieldBuilderV3<
          Orange, Orange.Builder, OrangeOrBuilder> orangeBuilder_;
      /**
       * <code>.Orange orange = 3;</code>
       */
      public boolean hasOrange() {
        return dataBodyCase_ == 3;
      }
      /**
       * <code>.Orange orange = 3;</code>
       */
      public Orange getOrange() {
        if (orangeBuilder_ == null) {
          if (dataBodyCase_ == 3) {
            return (Orange) dataBody_;
          }
          return Orange.getDefaultInstance();
        } else {
          if (dataBodyCase_ == 3) {
            return orangeBuilder_.getMessage();
          }
          return Orange.getDefaultInstance();
        }
      }
      /**
       * <code>.Orange orange = 3;</code>
       */
      public Builder setOrange(Orange value) {
        if (orangeBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          dataBody_ = value;
          onChanged();
        } else {
          orangeBuilder_.setMessage(value);
        }
        dataBodyCase_ = 3;
        return this;
      }
      /**
       * <code>.Orange orange = 3;</code>
       */
      public Builder setOrange(
          Orange.Builder builderForValue) {
        if (orangeBuilder_ == null) {
          dataBody_ = builderForValue.build();
          onChanged();
        } else {
          orangeBuilder_.setMessage(builderForValue.build());
        }
        dataBodyCase_ = 3;
        return this;
      }
      /**
       * <code>.Orange orange = 3;</code>
       */
      public Builder mergeOrange(Orange value) {
        if (orangeBuilder_ == null) {
          if (dataBodyCase_ == 3 &&
              dataBody_ != Orange.getDefaultInstance()) {
            dataBody_ = Orange.newBuilder((Orange) dataBody_)
                .mergeFrom(value).buildPartial();
          } else {
            dataBody_ = value;
          }
          onChanged();
        } else {
          if (dataBodyCase_ == 3) {
            orangeBuilder_.mergeFrom(value);
          }
          orangeBuilder_.setMessage(value);
        }
        dataBodyCase_ = 3;
        return this;
      }
      /**
       * <code>.Orange orange = 3;</code>
       */
      public Builder clearOrange() {
        if (orangeBuilder_ == null) {
          if (dataBodyCase_ == 3) {
            dataBodyCase_ = 0;
            dataBody_ = null;
            onChanged();
          }
        } else {
          if (dataBodyCase_ == 3) {
            dataBodyCase_ = 0;
            dataBody_ = null;
          }
          orangeBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>.Orange orange = 3;</code>
       */
      public Orange.Builder getOrangeBuilder() {
        return getOrangeFieldBuilder().getBuilder();
      }
      /**
       * <code>.Orange orange = 3;</code>
       */
      public OrangeOrBuilder getOrangeOrBuilder() {
        if ((dataBodyCase_ == 3) && (orangeBuilder_ != null)) {
          return orangeBuilder_.getMessageOrBuilder();
        } else {
          if (dataBodyCase_ == 3) {
            return (Orange) dataBody_;
          }
          return Orange.getDefaultInstance();
        }
      }
      /**
       * <code>.Orange orange = 3;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          Orange, Orange.Builder, OrangeOrBuilder>
          getOrangeFieldBuilder() {
        if (orangeBuilder_ == null) {
          if (!(dataBodyCase_ == 3)) {
            dataBody_ = Orange.getDefaultInstance();
          }
          orangeBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              Orange, Orange.Builder, OrangeOrBuilder>(
                  (Orange) dataBody_,
                  getParentForChildren(),
                  isClean());
          dataBody_ = null;
        }
        dataBodyCase_ = 3;
        onChanged();;
        return orangeBuilder_;
      }
      @Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      @Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:MyDataType)
    }

    // @@protoc_insertion_point(class_scope:MyDataType)
    private static final MyDataType DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new MyDataType();
    }

    public static MyDataType getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<MyDataType>
        PARSER = new com.google.protobuf.AbstractParser<MyDataType>() {
      @Override
      public MyDataType parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new MyDataType(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<MyDataType> parser() {
      return PARSER;
    }

    @Override
    public com.google.protobuf.Parser<MyDataType> getParserForType() {
      return PARSER;
    }

    @Override
    public MyDataType getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface AppleOrBuilder extends
      // @@protoc_insertion_point(interface_extends:Apple)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     * 生成int id 属性; 1 为属性的序号
     * </pre>
     *
     * <code>int32 id = 1;</code>
     */
    int getId();

    /**
     * <code>string orderCode = 2;</code>
     */
    String getOrderCode();
    /**
     * <code>string orderCode = 2;</code>
     */
    com.google.protobuf.ByteString
        getOrderCodeBytes();
  }
  /**
   * <pre>
   * 会在MsgOut 内部生成一个msg 内部类; 也就是正真发送的数据
   * </pre>
   *
   * Protobuf type {@code Apple}
   */
  public  static final class Apple extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:Apple)
      AppleOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Apple.newBuilder() to construct.
    private Apple(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Apple() {
      id_ = 0;
      orderCode_ = "";
    }

    @Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private Apple(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {

              id_ = input.readInt32();
              break;
            }
            case 18: {
              String s = input.readStringRequireUtf8();

              orderCode_ = s;
              break;
            }
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return MyFruitsOut.internal_static_Apple_descriptor;
    }

    @Override
    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return MyFruitsOut.internal_static_Apple_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              Apple.class, Builder.class);
    }

    public static final int ID_FIELD_NUMBER = 1;
    private int id_;
    /**
     * <pre>
     * 生成int id 属性; 1 为属性的序号
     * </pre>
     *
     * <code>int32 id = 1;</code>
     */
    public int getId() {
      return id_;
    }

    public static final int ORDERCODE_FIELD_NUMBER = 2;
    private volatile Object orderCode_;
    /**
     * <code>string orderCode = 2;</code>
     */
    public String getOrderCode() {
      Object ref = orderCode_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        orderCode_ = s;
        return s;
      }
    }
    /**
     * <code>string orderCode = 2;</code>
     */
    public com.google.protobuf.ByteString
        getOrderCodeBytes() {
      Object ref = orderCode_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        orderCode_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (id_ != 0) {
        output.writeInt32(1, id_);
      }
      if (!getOrderCodeBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, orderCode_);
      }
      unknownFields.writeTo(output);
    }

    @Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (id_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, id_);
      }
      if (!getOrderCodeBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, orderCode_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @Override
    public boolean equals(final Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof Apple)) {
        return super.equals(obj);
      }
      Apple other = (Apple) obj;

      boolean result = true;
      result = result && (getId()
          == other.getId());
      result = result && getOrderCode()
          .equals(other.getOrderCode());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + ID_FIELD_NUMBER;
      hash = (53 * hash) + getId();
      hash = (37 * hash) + ORDERCODE_FIELD_NUMBER;
      hash = (53 * hash) + getOrderCode().hashCode();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static Apple parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Apple parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Apple parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Apple parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Apple parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Apple parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Apple parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static Apple parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static Apple parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static Apple parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static Apple parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static Apple parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(Apple prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @Override
    protected Builder newBuilderForType(
        BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     * 会在MsgOut 内部生成一个msg 内部类; 也就是正真发送的数据
     * </pre>
     *
     * Protobuf type {@code Apple}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:Apple)
        AppleOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return MyFruitsOut.internal_static_Apple_descriptor;
      }

      @Override
      protected FieldAccessorTable
          internalGetFieldAccessorTable() {
        return MyFruitsOut.internal_static_Apple_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                Apple.class, Builder.class);
      }

      // Construct using netty.protobuf.MyFruitsOut.Apple.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @Override
      public Builder clear() {
        super.clear();
        id_ = 0;

        orderCode_ = "";

        return this;
      }

      @Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return MyFruitsOut.internal_static_Apple_descriptor;
      }

      @Override
      public Apple getDefaultInstanceForType() {
        return Apple.getDefaultInstance();
      }

      @Override
      public Apple build() {
        Apple result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @Override
      public Apple buildPartial() {
        Apple result = new Apple(this);
        result.id_ = id_;
        result.orderCode_ = orderCode_;
        onBuilt();
        return result;
      }

      @Override
      public Builder clone() {
        return (Builder) super.clone();
      }
      @Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      @Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      @Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      @Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      @Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      @Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof Apple) {
          return mergeFrom((Apple)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(Apple other) {
        if (other == Apple.getDefaultInstance()) return this;
        if (other.getId() != 0) {
          setId(other.getId());
        }
        if (!other.getOrderCode().isEmpty()) {
          orderCode_ = other.orderCode_;
          onChanged();
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @Override
      public final boolean isInitialized() {
        return true;
      }

      @Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        Apple parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (Apple) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private int id_ ;
      /**
       * <pre>
       * 生成int id 属性; 1 为属性的序号
       * </pre>
       *
       * <code>int32 id = 1;</code>
       */
      public int getId() {
        return id_;
      }
      /**
       * <pre>
       * 生成int id 属性; 1 为属性的序号
       * </pre>
       *
       * <code>int32 id = 1;</code>
       */
      public Builder setId(int value) {
        
        id_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * 生成int id 属性; 1 为属性的序号
       * </pre>
       *
       * <code>int32 id = 1;</code>
       */
      public Builder clearId() {
        
        id_ = 0;
        onChanged();
        return this;
      }

      private Object orderCode_ = "";
      /**
       * <code>string orderCode = 2;</code>
       */
      public String getOrderCode() {
        Object ref = orderCode_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          orderCode_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>string orderCode = 2;</code>
       */
      public com.google.protobuf.ByteString
          getOrderCodeBytes() {
        Object ref = orderCode_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          orderCode_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string orderCode = 2;</code>
       */
      public Builder setOrderCode(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        orderCode_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string orderCode = 2;</code>
       */
      public Builder clearOrderCode() {
        
        orderCode_ = getDefaultInstance().getOrderCode();
        onChanged();
        return this;
      }
      /**
       * <code>string orderCode = 2;</code>
       */
      public Builder setOrderCodeBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        orderCode_ = value;
        onChanged();
        return this;
      }
      @Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      @Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:Apple)
    }

    // @@protoc_insertion_point(class_scope:Apple)
    private static final Apple DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new Apple();
    }

    public static Apple getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Apple>
        PARSER = new com.google.protobuf.AbstractParser<Apple>() {
      @Override
      public Apple parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Apple(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Apple> parser() {
      return PARSER;
    }

    @Override
    public com.google.protobuf.Parser<Apple> getParserForType() {
      return PARSER;
    }

    @Override
    public Apple getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface OrangeOrBuilder extends
      // @@protoc_insertion_point(interface_extends:Orange)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string sku = 1;</code>
     */
    String getSku();
    /**
     * <code>string sku = 1;</code>
     */
    com.google.protobuf.ByteString
        getSkuBytes();

    /**
     * <code>int32 price = 2;</code>
     */
    int getPrice();
  }
  /**
   * Protobuf type {@code Orange}
   */
  public  static final class Orange extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:Orange)
      OrangeOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Orange.newBuilder() to construct.
    private Orange(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Orange() {
      sku_ = "";
      price_ = 0;
    }

    @Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private Orange(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              String s = input.readStringRequireUtf8();

              sku_ = s;
              break;
            }
            case 16: {

              price_ = input.readInt32();
              break;
            }
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return MyFruitsOut.internal_static_Orange_descriptor;
    }

    @Override
    protected FieldAccessorTable
        internalGetFieldAccessorTable() {
      return MyFruitsOut.internal_static_Orange_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              Orange.class, Builder.class);
    }

    public static final int SKU_FIELD_NUMBER = 1;
    private volatile Object sku_;
    /**
     * <code>string sku = 1;</code>
     */
    public String getSku() {
      Object ref = sku_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        sku_ = s;
        return s;
      }
    }
    /**
     * <code>string sku = 1;</code>
     */
    public com.google.protobuf.ByteString
        getSkuBytes() {
      Object ref = sku_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (String) ref);
        sku_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int PRICE_FIELD_NUMBER = 2;
    private int price_;
    /**
     * <code>int32 price = 2;</code>
     */
    public int getPrice() {
      return price_;
    }

    private byte memoizedIsInitialized = -1;
    @Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getSkuBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, sku_);
      }
      if (price_ != 0) {
        output.writeInt32(2, price_);
      }
      unknownFields.writeTo(output);
    }

    @Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getSkuBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, sku_);
      }
      if (price_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, price_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @Override
    public boolean equals(final Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof Orange)) {
        return super.equals(obj);
      }
      Orange other = (Orange) obj;

      boolean result = true;
      result = result && getSku()
          .equals(other.getSku());
      result = result && (getPrice()
          == other.getPrice());
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + SKU_FIELD_NUMBER;
      hash = (53 * hash) + getSku().hashCode();
      hash = (37 * hash) + PRICE_FIELD_NUMBER;
      hash = (53 * hash) + getPrice();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static Orange parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Orange parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Orange parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Orange parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Orange parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static Orange parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static Orange parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static Orange parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static Orange parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static Orange parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static Orange parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static Orange parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(Orange prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @Override
    protected Builder newBuilderForType(
        BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code Orange}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:Orange)
        OrangeOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return MyFruitsOut.internal_static_Orange_descriptor;
      }

      @Override
      protected FieldAccessorTable
          internalGetFieldAccessorTable() {
        return MyFruitsOut.internal_static_Orange_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                Orange.class, Builder.class);
      }

      // Construct using netty.protobuf.MyFruitsOut.Orange.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @Override
      public Builder clear() {
        super.clear();
        sku_ = "";

        price_ = 0;

        return this;
      }

      @Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return MyFruitsOut.internal_static_Orange_descriptor;
      }

      @Override
      public Orange getDefaultInstanceForType() {
        return Orange.getDefaultInstance();
      }

      @Override
      public Orange build() {
        Orange result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @Override
      public Orange buildPartial() {
        Orange result = new Orange(this);
        result.sku_ = sku_;
        result.price_ = price_;
        onBuilt();
        return result;
      }

      @Override
      public Builder clone() {
        return (Builder) super.clone();
      }
      @Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.setField(field, value);
      }
      @Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      @Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      @Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      @Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      @Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof Orange) {
          return mergeFrom((Orange)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(Orange other) {
        if (other == Orange.getDefaultInstance()) return this;
        if (!other.getSku().isEmpty()) {
          sku_ = other.sku_;
          onChanged();
        }
        if (other.getPrice() != 0) {
          setPrice(other.getPrice());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @Override
      public final boolean isInitialized() {
        return true;
      }

      @Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        Orange parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (Orange) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private Object sku_ = "";
      /**
       * <code>string sku = 1;</code>
       */
      public String getSku() {
        Object ref = sku_;
        if (!(ref instanceof String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          String s = bs.toStringUtf8();
          sku_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      /**
       * <code>string sku = 1;</code>
       */
      public com.google.protobuf.ByteString
          getSkuBytes() {
        Object ref = sku_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (String) ref);
          sku_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string sku = 1;</code>
       */
      public Builder setSku(
          String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        sku_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string sku = 1;</code>
       */
      public Builder clearSku() {
        
        sku_ = getDefaultInstance().getSku();
        onChanged();
        return this;
      }
      /**
       * <code>string sku = 1;</code>
       */
      public Builder setSkuBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        sku_ = value;
        onChanged();
        return this;
      }

      private int price_ ;
      /**
       * <code>int32 price = 2;</code>
       */
      public int getPrice() {
        return price_;
      }
      /**
       * <code>int32 price = 2;</code>
       */
      public Builder setPrice(int value) {
        
        price_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 price = 2;</code>
       */
      public Builder clearPrice() {
        
        price_ = 0;
        onChanged();
        return this;
      }
      @Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      @Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:Orange)
    }

    // @@protoc_insertion_point(class_scope:Orange)
    private static final Orange DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new Orange();
    }

    public static Orange getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Orange>
        PARSER = new com.google.protobuf.AbstractParser<Orange>() {
      @Override
      public Orange parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Orange(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Orange> parser() {
      return PARSER;
    }

    @Override
    public com.google.protobuf.Parser<Orange> getParserForType() {
      return PARSER;
    }

    @Override
    public Orange getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_MyDataType_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_MyDataType_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Apple_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Apple_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Orange_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Orange_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    String[] descriptorData = {
      "\n\021MyFruitsOut.proto\"\240\001\n\nMyDataType\022\'\n\tda" +
      "ta_type\030\001 \001(\0162\024.MyDataType.DataType\022\027\n\005a" +
      "pple\030\002 \001(\0132\006.AppleH\000\022\031\n\006orange\030\003 \001(\0132\007.O" +
      "rangeH\000\")\n\010DataType\022\r\n\tAppleType\020\000\022\016\n\nOr" +
      "angeTyoe\020\001B\n\n\010dataBody\"&\n\005Apple\022\n\n\002id\030\001 " +
      "\001(\005\022\021\n\torderCode\030\002 \001(\t\"$\n\006Orange\022\013\n\003sku\030" +
      "\001 \001(\t\022\r\n\005price\030\002 \001(\005B\037\n\016netty.protobufB\013" +
      "MyFruitsOutH\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_MyDataType_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_MyDataType_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_MyDataType_descriptor,
        new String[] { "DataType", "Apple", "Orange", "DataBody", });
    internal_static_Apple_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_Apple_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Apple_descriptor,
        new String[] { "Id", "OrderCode", });
    internal_static_Orange_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_Orange_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Orange_descriptor,
        new String[] { "Sku", "Price", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
